#! /bin/sh

# Apps
#pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
sxhkd &
nm-applet &
# microsoft-edge-dev &
/usr/bin/dunst &
$HOME/.fehbg &
$HOME/.config/polybar/launch.sh 
picom -b &
# feh --bg-fill /usr/share/backgrounds/bspwm/wall.png


# Bsp config
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a system-config-printer state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# pywal colors config
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
